### PR TITLE
Add Angular UI

### PR DESCRIPTION
**Pull request by martinbreu**
Angular is not reachable under http://localhost/search
Can you help me?

### CODE REVIEW

**Comment by BjoernKrollGba** [comment]
> Angular is not reachable under http://localhost/search
> Can you help me?

Try http://localhost:8085/search

**Comment by martinbreu** [comment]
> Try http://localhost:8085/search

I did not configure any ports, so port 80 should be exposed: https://github.com/samply/sample-locator/blob/672a252e706c59a77e8c3778d9552351e47eda2b/Dockerfile#L11

**Comment by alexanderkiel** [comment]
The Angular UI is nor build to run under a context path. It needs to run without any context path like `search`. I would just replace the JSF UI with the Angular UI and run the Angular UI without a context path.

**Comment by martinbreu** [comment]
The Angular UI did not show up with any configuration. But formating the environments has worked out :)

**Comment by alexanderkiel** [comment]
It did show up as empty white page. Because the Javascript couldn't be loaded.

**Comment by alexanderkiel** [comment]
Now you just exported the Angular UI on its separate port 8085 without using the Nginx reverse proxy. Is that it what we want?

**Review by alexanderkiel — CHANGES_REQUESTED** [review]
I already commented.

**Comment by martinbreu** [comment]
> Now you just exported the Angular UI on its separate port 8085 without using the Nginx reverse proxy. Is that it what we want?

The javascript could not be loaded because of wrong formated environments, however, would you prefer to delete the JSF-UI and use the Nginx for Angular??

**Comment by alexanderkiel** [comment]
Yes I would prefer to remove the JSF UI. Do you think we need the Angular UI any time longer?

**Comment by martinbreu** [comment]
> Yes I would prefer to remove the JSF UI. Do you think we need the Angular UI any time longer?

You mean we do not need the JSF UI any longer?

**Comment by alexanderkiel** [comment]
>You mean we do not need the JSF UI any longer?

Yes, why would we?

**Pull request merged**
